### ISSUE TITLE
Error while build

### ISSUE THREAD

**Issue by Ygarr** [KodeMunkie/imagetozxspec#1]
Error while "mvn package" run. But  result "Built succeful" anyway
`Running uk.co.silentsoftware.core.colourstrategy.ColourChoiceStrategyTest
2020-02-16 06:08:29 INFO  OptionsObject:402 - Options initialised
2020-02-16 06:08:29 DEBUG HumbleVideoImportEngine:187 - Path to library Optional.empty
2020-02-16 06:08:29 DEBUG HumbleVideoImportEngine:195 - Linux OS
2020-02-16 06:08:29 DEBUG HumbleVideoImportEngine:229 - Resource name: libhumblevideo.so
2020-02-16 06:08:29 WARN  HumbleVideoImportEngine:233 - Unable to expose library libhumblevideo.so
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.nio.file.Files.copy(Files.java:2984)
	at uk.co.silentsoftware.core.converters.video.HumbleVideoImportEngine.copyLibraryResources(HumbleVideoImportEngine.java:249)
	at uk.co.silentsoftware.core.converters.video.HumbleVideoImportEngine.exposeNativeLibrary(HumbleVideoImportEngine.java:230)
	at uk.co.silentsoftware.core.converters.video.HumbleVideoImportEngine.lambda$initVideoImportEngine$0(HumbleVideoImportEngine.java:196)
	at java.lang.Thread.run(Thread.java:748)
2020-02-16 06:08:29 ERROR JNILibraryLoader:273 - Could not load library: humblevideo; version: 0.
2020-02-16 06:08:29 ERROR HumbleVideoImportEngine:209 - Unable to load native library
java.lang.UnsatisfiedLinkError: no humblevideo in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at io.humble.ferry.JNILibraryLoader.loadLibrary0(JNILibraryLoader.java:268)
	at io.humble.ferry.JNILibraryLoader.loadLibrary(JNILibraryLoader.java:171)
	at io.humble.ferry.JNILibrary.load(JNILibrary.java:152)
	at io.humble.ferry.FerryJNI.<clinit>(FerryJNI.java:16)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at uk.co.silentsoftware.core.converters.video.HumbleVideoImportEngine.lambda$initVideoImportEngine$0(HumbleVideoImportEngine.java:207)
	at java.lang.Thread.run(Thread.java:748)
`
Os: manjaro linux
java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
mvn -v
Apache Maven 3.6.3 (NON-CANONICAL_2019-11-27T20:26:29Z_root)
Maven home: /opt/maven
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.19.102-1-manjaro", arch: "amd64", family: "unix"

**Comment by KodeMunkie** [comment]
Did you build (package) with the "linux" profile selected?

**Comment by Ygarr** [comment]
Thanks!Obliged. 
Now with:
"`mvn build -P linux-x64`"
Everything seems ok!

**Comment by KodeMunkie** [comment]
Resolved - profile not selected for build.
